language: clojure
script: "lein midje"
before_script:
  - ./scripts/UpdateGeoIpFiles.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bfd7e356ba6e7f4a8fbb
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
